post_install() {
  echo
  echo "  To prevent conflicts with other emoji fonts, 70-emojione.conf is not being automatically installed in /etc/fonts/conf.d/"
  echo
  echo "  If you don't use other emoji fonts, simply make a symlink:"
  echo "  $ ln -sf ../conf.avail/70-emojione.conf /etc/fonts/conf.d/70-emojione.conf"
  echo
  echo "  If you do use other emoji fonts, copy 70-emojione.conf to /etc/fonts/conf.d/ and remove corresponding aliases."
  echo
}

post_upgrade() {
  post_install
}
